CREATE USER shop IDENTIFIED BY shop;

GRANT SELECT_CATALOG_ROLE      TO shop;
GRANT CREATE JOB               TO shop;
GRANT CREATE MATERIALIZED VIEW TO shop;
GRANT CREATE PROCEDURE         TO shop;
GRANT CREATE SEQUENCE          TO shop;
GRANT CREATE SESSION           TO shop;
GRANT CREATE SYNONYM           TO shop;
GRANT CREATE TABLE             TO shop;
GRANT CREATE TRIGGER           TO shop;
GRANT CREATE TYPE              TO shop;
GRANT CREATE VIEW              TO shop;
GRANT QUERY REWRITE            TO shop;
GRANT UNLIMITED TABLESPACE     TO shop;
ALTER USER shop DEFAULT ROLE ALL;